spring:
  application:
    name: HRBank
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  datasource: # H2 DB 연동
    url: jdbc:h2:mem:hrbank;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #JPA
  jpa:
    hibernate:
      ddl-auto: update # 개발/테스트용 H2에서는 update나 create 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC

# swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    persist-authorization: true

#log
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace

hrbank:
  storage:
    type: local
    local:
      root-path: .hrbank/storage
